version: "3.8"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/db:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"

  odoo:
    image: odoo:16.0
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8069"
    volumes:
      - ./volumes/odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "1G"
        reservations:
          cpus: "0.50"
          memory: "512M"
